name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: devsocial
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: testsecret
      DEBUG: False
      ALLOWED_HOSTS: localhost,127.0.0.1
      DB_NAME: devsocial
      DB_USER: devuser
      DB_PASSWORD: devpassword
      DB_HOST: localhost
      DB_PORT: 5432
      DATABASE_URL: postgres://devuser:devpassword@localhost:5432/devsocial

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          cd backend
          pytest